version: "3.9"

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
      - .development.env
    ports:
      - 5432:5432
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    restart: always
